### PR TITLE
Fix configuration adapter

### LINKED ISSUE #24: (Combination) of configuration options does not work
We are trying out visual configurations of PSPDFKit (for Ionic/Angular/Cordova) and on the custom configuration options suggested [here](https://github.com/PSPDFKit/PSPDFKit-Cordova/tree/master/docs/android#options) we are getting runtime errors upon initializing the plugin, telling that a particular value is not valid (thus needed to be commented out or changed to default value). For us it worked only after initializing with empty options or reducing the number of options to what you see here (what is not commented out):

```typescript
    const options: PSPDFKitOptions = {
        backgroundColor: "#EFEFEF", // hex-color of the page background
        // disableAnnotationList: false, // hide annotation list (default: false)
        disableAnnotationNoteHinting: false, // hide small notes next to annotations that have a text set (default: false)
        // disableBookmarkEditing: false, // hide bookmark editing (default: false)
        // disableBookmarkList: false, // hide bookmark list (default: false)
        disableCopyPaste: false, // disable annotation copy/paste (default: false)
        // disableDocumentEditor: false, // hide document editor (default: false)
        // disableOutline: false, // hide the outline menu (default: false)
        // disablePrinting: false, // hide option to print (default: false)
        disableUndoRedo: false, // disable undo/redo system (default: false)
        // hidePageLabels: false, // hide page labels (if available in PDF) in page overlay and thumbnail grid (default: false)
        // // hidePageNumberOverlay: false, // hide the overlay showing the current page (default: false)
        // // hideSettingsMenu: false, // hide the settings menu (default: false)
        // // thumbnailBarMode: PSPDFKit.ThumbnailBarMode.THUMBNAIL_BAR_MODE_DEFAULT, // show static thumbnail bar. Also valid: THUMBNAIL_BAR_MODE_DEFAULT, THUMBNAIL_BAR_MODE_SCROLLABLE
        // // hideThumbnailGrid: false, // hide the thumbnail grid menu (default: false)
        pageFitMode: PSPDFKit.PageFitMode.FIT_TO_WIDTH, // also valid: PSPDFKit.PageFitMode.FIT_TO_SCREEN
        // scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL, // also valid: PSPDFKit.PageScrollDirection.HORIZONTAL
        // scrollMode: PSPDFKit.ScrollMode.CONTINUOUS, // also valid: PSPDFKit.ScrollMode.PER_PAGE
        // // Configures which share actions should be visible in the user interface. (default: all enabled)
        shareFeatures: [
            /** Document sharing inside the activity. */
            PSPDFKit.ShareFeatures.DOCUMENT_SHARING,
            /** Sharing of embedded files (on file annotations). */
            PSPDFKit.ShareFeatures.EMBEDDED_FILE_SHARING,
            /** Sharing of text from selected free text annotations. */
            PSPDFKit.ShareFeatures.FREE_TEXT_ANNOTATION_SHARING,
            /** Sharing of selected image annotations. */
            PSPDFKit.ShareFeatures.IMAGE_SHARING,
            /** Sharing of text from selected note annotations. */
            PSPDFKit.ShareFeatures.NOTE_ANNOTATION_SHARING,
            /** Sharing of text from annotation contents or comments. */
            PSPDFKit.ShareFeatures.NOTE_EDITOR_CONTENT_SHARING,
            /** Sharing of selected text. */
            PSPDFKit.ShareFeatures.TEXT_SELECTION_SHARING
        ],
        invertColors: false, // invert rendered colors (default: false)
        toGrayscale: false, // render document in grayscale only (default: false)
        // startZoomScale: 2.0, // initial zoom value (default: 1.0)
        // maxZoomScale: 10.0, // maximum zoom factor when zooming into a page (default: 15.0)
        zoomOutBounce: true, // "bounce" animation when pinch-zooming out (default: true)
        // page: 2, // initial page number (default: 0, i.e. the first page)
        useImmersiveMode: false, // activate Android's immersive app mode (default: false)
        // disableSearch: false, // completely deactivate document search (default: false)
        // searchType: PSPDFKit.SearchType.SEARCH_MODULAR, // also valid: PSPDFKit.SearchType.SEARCH_INLINE
        // autosaveEnabled: true, // automatically save document changes on exit (default: true)
        // annotationEditing: {
        //     enabled: true, // activate annotation editing (default: true)
        //     creatorName: "John Doe" // author name written into new annotations (default: null)
        // }
    };
        PSPDFKit.present(path, options, () => {}, () => {});
```
Do the options work only in certain combinations or are they deprecated and the docs need to be updated?

We are using `"pspdfkit-cordova": "1.0.9"` with ionic 4 and cordova 9

### PR DESCRIPTION
**Pull request by davidschreiber**
# Details

Resolves #24. Some of our configuration options where behaving unexpectedly when used with the default options. This also fixes the mapping between thumbnail bar enum types that was no longer correct since we merged public iOS and Android APIs.

# Acceptance Criteria

- [x] When approved, right before merging, rebase with master and increment the package version in `package.json` and `plugin.xml`(see example commit: https://github.com/PSPDFKit/PSPDFKit-Cordova/commit/09d5c6b1c12977dc2248c02d869c3247ff5ed6f5).
- [ ] Create a new release (and tag) with the new package version (see https://github.com/PSPDFKit/PSPDFKit-Cordova/releases).
- [ ] Locally, pull the latest master and publish (`npm publish`) the new release to [npm](https://www.npmjs.com/package/pspdfkit-cordova).

### CODE REVIEW

File: src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java [hunk 1]
```diff
@@ -95,39 +95,87 @@ private PdfActivityConfiguration parseOptionsToConfiguration(@NonNull final JSON
...
         } else if ("backgroundColor".equals(option)) {
           builder.backgroundColor(Color.parseColor((String) value));
-        } else if ("disableAnnotationList".equals(option) && ((Boolean) value)) {
-          builder.disableAnnotationList();
+        } else if ("disableAnnotationList".equals(option)) {
+          if (((Boolean) value)) {
+            builder.disableAnnotationList();
+          } else {
+            builder.enableAnnotationList();
+          }
```
Comment (davidschreiber) [inline src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java:103]: The previous implementation could not differentiate between a mismatch of the option name and a `false` value, which lead to exception due to the "catch unknown properties" code further below.

File: src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java [hunk 2]
```diff
@@ -95,39 +95,87 @@ private PdfActivityConfiguration parseOptionsToConfiguration(@NonNull final JSON
...
+            builder.hideSettingsMenu();
+          } else {
+            builder.showSettingsMenu();
+          }
         } else if ("thumbnailBarMode".equals(option)) {
-          builder.setThumbnailBarMode(ThumbnailBarMode.valueOf((String) value));
-        } else if ("hideThumbnailGrid".equals(option) && ((Boolean) value)) {
-          builder.hideThumbnailGrid();
+          final CordovaThumbnailBarMode thumbnailBarMode = CordovaThumbnailBarMode.valueOf((String) value);
+          builder.setThumbnailBarMode(thumbnailBarMode.androidThumbnailBarMode);
```
Comment (davidschreiber) [inline src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java:172]: While merging the iOS and Android plugins into this repo, we changed the public API name for thumbnail bar options, leading to an error here. I added an adapter enum for mapping between JS and Android names.

File: src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java [hunk 3]
```diff
@@ -95,39 +95,87 @@ private PdfActivityConfiguration parseOptionsToConfiguration(@NonNull final JSON
           builder.autosaveEnabled((Boolean) value);
         } else if ("backgroundColor".equals(option)) {
           builder.backgroundColor(Color.parseColor((String) value));
-        } else if ("disableAnnotationList".equals(option) && ((Boolean) value)) {
-          builder.disableAnnotationList();
+        } else if ("disableAnnotationList".equals(option)) {
+          if (((Boolean) value)) {
```
Comment (skoric) [inline src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java:99]: If I'm seeing correctly, there's an extra parenthesis here and in few places below.

Comment (davidschreiber) [reply src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java:99]: Good catch 👍
